[build]
  command = "npm run build"
  publish = ".next"

[functions]
  directory = "netlify/functions"
  external_node_modules = ["sharp"]
  included_files = ["node_modules/sharp/**", "node_modules/@img/**"]

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/media/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"
